export const ActionTypes = {
    GET_CHILDS_LIST: "GET_CHILDS_LIST",
    CHILDS_SUCCESS: "CHILDS_SUCCESS",
    CHILDS_ERROR: "CHILDS_ERROR",
    GET_CART_ITEMS: "GET_CART_ITEMS",
    CART_LIST_SUCCESS: "CART_LIST_SUCCESS",
    CART_LIST_ERROR: "CART_LIST_ERROR",
    SET_LOCATION: "SET_LOCATION",
    GET_LOCATION: "GET_LOCATION",
};